--- #YAML:1.0
name:               Hash-Merge
version:            0.11
abstract:           Merges arbitrarily deep hashes into a single hash
author:
    - Michael K. Neylon <mneylon-pm@masemware.com
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Clone:       0
    Test::More:  0.33
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
