---
abstract: 'Merges arbitrarily deep hashes into a single hash'
author:
  - 'Michael K. Neylon <mneylon-pm@masemware.com'
build_requires:
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Merge
no_index:
  directory:
    - t
    - inc
requires:
  Clone: 0
  perl: v5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.200
